name: buildDocker

on:
  push:
    tags:
      - '*'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry node
      pre: echo ::save-state name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: wanrenzhizun/bookstack
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest,${{ env.STATE_RELEASE_VERSION }}_node"
        dockerfile: Dockerfile.node
    - name: Publish to Registry alpine
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: wanrenzhizun/bookstack
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest_alpine,${{ env.STATE_RELEASE_VERSION }}_alpine"
        dockerfile: Dockerfile.alpine
